from pydantic import BaseModel


class HealthCheck(BaseModel):
    check_id: str
    name: str
    source: str
    default_frequency: str
    failure_outcome: str
    mandatory: bool = True
    domain: str
    severity: str
    evidence_artifact: str
    required_permission: str
    remediation_hint: str
    production_gate_impact: str


class HealthCatalogue(BaseModel):
    version: str
    checks: list[HealthCheck]


def check(
    check_id: str,
    name: str,
    domain: str,
    source: str,
    default_frequency: str,
    failure_outcome: str,
    evidence_artifact: str,
    remediation_hint: str,
    production_gate_impact: str,
    *,
    severity: str | None = None,
    required_permission: str = "view_dashboard",
    mandatory: bool = True,
) -> HealthCheck:
    return HealthCheck(
        check_id=check_id,
        name=name,
        domain=domain,
        source=source,
        default_frequency=default_frequency,
        failure_outcome=failure_outcome,
        severity=severity or failure_outcome,
        evidence_artifact=evidence_artifact,
        required_permission=required_permission,
        remediation_hint=remediation_hint,
        production_gate_impact=production_gate_impact,
        mandatory=mandatory,
    )


def default_catalogue() -> HealthCatalogue:
    return HealthCatalogue(
        version="2026.09.assurance-expanded",
        checks=[
            check(
                "HC-001",
                "Prism endpoint reachability",
                "Platform Reachability",
                "HTTPS",
                "5 minutes",
                "UNKNOWN",
                "connection_probe",
                "Verify network path, port 9440 access, DNS/IP routing and proxy/firewall rules.",
                "Blocks all production assurance when no Prism endpoint can be reached.",
            ),
            check(
                "HC-002",
                "Cluster availability",
                "Cluster Health",
                "Prism API",
                "Daily",
                "CRITICAL",
                "inventory_run.clusters",
                "Confirm the cluster appears in Prism, is reachable and reports an operational lifecycle state.",
                "Blocks health sign-off for the affected cluster.",
            ),
            check(
                "HC-003",
                "Host availability",
                "Host / CVM",
                "Prism API",
                "Daily",
                "CRITICAL",
                "domain_collector.hardware",
                "Investigate unavailable hosts, maintenance mode and hypervisor/CVM connectivity.",
                "Blocks production readiness when host availability cannot be proven.",
            ),
            check(
                "HC-004",
                "CVM availability",
                "Host / CVM",
                "Prism API or NCC",
                "Daily",
                "CRITICAL",
                "domain_collector.hardware",
                "Confirm CVM power, network, memory and core Nutanix service posture.",
                "Blocks production readiness when CVM availability cannot be proven.",
            ),
            check(
                "HC-005",
                "API authentication validity",
                "Platform Reachability",
                "Prism API",
                "5 minutes",
                "UNKNOWN",
                "connection_probe",
                "Rotate the stored Prism credential or adjust Prism role permissions.",
                "Blocks trusted evidence collection until credentials are valid.",
            ),
            check(
                "HC-006",
                "TLS certificate trust and expiry",
                "Platform Reachability",
                "TLS",
                "Daily",
                "WARNING",
                "connection_probe",
                "Install a trusted certificate chain or document lab-only insecure mode evidence.",
                "Prevents production claims when TLS verification is skipped or expiring.",
            ),
            check(
                "HC-007",
                "Prism Central / Element identity consistency",
                "Platform Reachability",
                "Prism API",
                "Daily",
                "WARNING",
                "inventory_run.clusters",
                "Compare cluster UUIDs and names across Prism Central and Prism Element collectors.",
                "Flags ambiguous estate evidence and duplicate/incorrect target selection.",
            ),
            check(
                "HC-008",
                "AOS and Prism version collected",
                "Platform Reachability",
                "Prism API",
                "Daily",
                "WARNING",
                "inventory_run.clusters",
                "Confirm version fields are returned and retained in evidence.",
                "Required for supportability and compatibility evidence.",
            ),
            check(
                "HC-009",
                "Time synchronization health",
                "Platform Reachability",
                "Prism API or NCC",
                "Daily",
                "WARNING",
                "ncc_or_inventory_time",
                "Validate NTP status and clock skew before trusting schedule/audit evidence.",
                "Blocks strong audit/evidence claims when clock state is unknown.",
            ),
            check(
                "HC-010",
                "Cluster quorum and metadata services",
                "Cluster Health",
                "Prism API or NCC",
                "Daily",
                "CRITICAL",
                "ncc_cluster_health",
                "Review quorum, metadata service and core cluster service health.",
                "Blocks production readiness when core cluster services are degraded.",
            ),
            check(
                "HC-011",
                "Critical alerts present",
                "Cluster Health",
                "Prism API",
                "Hourly",
                "CRITICAL",
                "alerts_collector",
                "Triage active critical alerts before closing readiness gates.",
                "Blocks readiness while unacknowledged critical alerts exist.",
            ),
            check(
                "HC-012",
                "Recent critical events",
                "Cluster Health",
                "Prism API",
                "Hourly",
                "WARNING",
                "events_collector",
                "Review recent critical events and attach event evidence to the run.",
                "Requires operator review before production claims.",
            ),
            check(
                "HC-013",
                "Redundancy factor compliance",
                "Cluster Health",
                "Prism API or NCC",
                "Daily",
                "CRITICAL",
                "resiliency_collector",
                "Validate RF/resiliency posture and repair degraded replicas.",
                "Blocks readiness when resiliency cannot tolerate expected failures.",
            ),
            check(
                "HC-014",
                "Storage pool usage threshold",
                "Storage",
                "Prism API",
                "Hourly",
                "WARNING",
                "domain_collector.storage",
                "Add capacity, rebalance or resolve abnormal growth before threshold breach.",
                "Flags capacity risk and may block depending on threshold policy.",
            ),
            check(
                "HC-015",
                "Container usage threshold",
                "Storage",
                "Prism API",
                "Hourly",
                "WARNING",
                "domain_collector.storage",
                "Review high-use containers and snapshot/data growth contributors.",
                "Flags capacity risk for affected workloads.",
            ),
            check(
                "HC-016",
                "Application self-health",
                "Operations",
                "Internal",
                "1 minute",
                "CRITICAL",
                "support_status",
                "Check API mode, database status, evidence directory and collector failures.",
                "Blocks assurance claims when the orchestrator cannot trust itself.",
            ),
            check(
                "HC-017",
                "Disk online and fault state",
                "Storage",
                "Prism API",
                "Daily",
                "CRITICAL",
                "domain_collector.hardware",
                "Replace or repair failed/offline disks and verify rebuild progress.",
                "Blocks readiness when disk fault evidence is active or unknown.",
            ),
            check(
                "HC-018",
                "CVM disk usage",
                "Host / CVM",
                "Prism API or NCC",
                "Daily",
                "WARNING",
                "ncc_or_hardware_collector",
                "Free CVM disk pressure or follow vendor-guided remediation.",
                "Requires support review before readiness closure.",
            ),
            check(
                "HC-019",
                "Host maintenance mode",
                "Host / CVM",
                "Prism API",
                "Daily",
                "WARNING",
                "domain_collector.hardware",
                "Confirm maintenance intent or return the host to service.",
                "Flags reduced capacity and resiliency.",
            ),
            check(
                "HC-020",
                "Host count minimum",
                "Host / CVM",
                "Prism API",
                "Daily",
                "CRITICAL",
                "domain_collector.hardware",
                "Validate node count against the expected design and resiliency target.",
                "Blocks readiness when the cluster is below the required topology.",
            ),
            check(
                "HC-021",
                "Host NIC link state",
                "Network",
                "Prism API",
                "Hourly",
                "CRITICAL",
                "domain_collector.network",
                "Investigate disconnected NICs, switch ports, bonds and cabling.",
                "Blocks readiness for affected hosts or networks.",
            ),
            check(
                "HC-022",
                "CVM network reachability",
                "Network",
                "Prism API or NCC",
                "Hourly",
                "CRITICAL",
                "domain_collector.network",
                "Verify CVM management/storage network reachability.",
                "Blocks readiness when CVM network paths are impaired.",
            ),
            check(
                "HC-023",
                "DNS resolution",
                "Network",
                "Internal",
                "Daily",
                "WARNING",
                "support_status",
                "Verify configured names resolve from the orchestrator runtime.",
                "Prevents stable scheduled collection when DNS is unreliable.",
            ),
            check(
                "HC-024",
                "Gateway reachability",
                "Network",
                "Internal",
                "Daily",
                "WARNING",
                "support_status",
                "Validate routing from the appliance to configured Prism endpoints.",
                "Flags network dependency risk for collection and alerting.",
            ),
            check(
                "HC-025",
                "MTU consistency",
                "Network",
                "Prism API or NCC",
                "Weekly",
                "WARNING",
                "ncc_network",
                "Compare expected MTU to host/CVM/network evidence.",
                "Requires operator review for throughput-sensitive workloads.",
                mandatory=False,
            ),
            check(
                "HC-026",
                "CPU headroom",
                "Capacity",
                "Prism API",
                "Daily",
                "WARNING",
                "domain_collector.capacity",
                "Review CPU utilization and growth trend before threshold breach.",
                "Flags capacity risk for planning and alerting.",
            ),
            check(
                "HC-027",
                "Memory headroom",
                "Capacity",
                "Prism API",
                "Daily",
                "WARNING",
                "domain_collector.capacity",
                "Review memory pressure, ballooning/swapping indicators and workload growth.",
                "Flags capacity risk for planning and alerting.",
            ),
            check(
                "HC-028",
                "Storage runway estimate",
                "Capacity",
                "Prism API",
                "Daily",
                "WARNING",
                "domain_collector.capacity",
                "Calculate capacity runway once enough historical evidence exists.",
                "Required before forecast-based production alerting.",
            ),
            check(
                "HC-029",
                "Hotspot detection",
                "Capacity",
                "Prism API",
                "Daily",
                "WARNING",
                "domain_collector.capacity",
                "Review node/cluster imbalance and rebalance where appropriate.",
                "Flags uneven capacity or performance risk.",
                mandatory=False,
            ),
            check(
                "HC-030",
                "Protection domain status",
                "Data Protection",
                "Prism API",
                "Daily",
                "CRITICAL",
                "data_protection_collector",
                "Validate protection domain health and resolve failed protection jobs.",
                "Blocks readiness for protected workloads when status is unhealthy.",
            ),
            check(
                "HC-031",
                "Snapshot schedule status",
                "Data Protection",
                "Prism API",
                "Daily",
                "WARNING",
                "data_protection_collector",
                "Confirm snapshot schedules are enabled and aligned to policy.",
                "Flags backup/RPO evidence gaps.",
            ),
            check(
                "HC-032",
                "Last successful snapshot age",
                "Data Protection",
                "Prism API",
                "Hourly",
                "CRITICAL",
                "data_protection_collector",
                "Investigate overdue snapshots or replication delays.",
                "Blocks RPO readiness when snapshot age exceeds policy.",
            ),
            check(
                "HC-033",
                "Remote site reachability",
                "Data Protection",
                "Prism API",
                "Daily",
                "WARNING",
                "data_protection_collector",
                "Validate remote site connection and replication transport.",
                "Flags disaster recovery evidence gaps.",
            ),
            check(
                "HC-034",
                "Local RBAC password coverage",
                "Security / Governance",
                "Internal",
                "Daily",
                "CRITICAL",
                "rbac_store",
                "Set passwords for all active local users and disable unused accounts.",
                "Blocks admin readiness when active users lack credentials.",
            ),
            check(
                "HC-035",
                "Admin role count",
                "Security / Governance",
                "Internal",
                "Daily",
                "WARNING",
                "rbac_store",
                "Review admin assignment count and remove unnecessary privileged access.",
                "Flags governance risk for operational handover.",
            ),
            check(
                "HC-036",
                "Audit log activity",
                "Security / Governance",
                "Internal",
                "Daily",
                "WARNING",
                "audit_store",
                "Confirm sensitive changes are recorded and retained.",
                "Required for supportability and change traceability.",
            ),
            check(
                "HC-037",
                "Prism credential age",
                "Security / Governance",
                "Internal",
                "Weekly",
                "WARNING",
                "connection_store",
                "Rotate old Prism credentials according to local policy.",
                "Flags secret hygiene risk.",
                mandatory=False,
            ),
            check(
                "HC-038",
                "Insecure TLS mode production gate",
                "Security / Governance",
                "Internal",
                "Daily",
                "CRITICAL",
                "support_status",
                "Switch to strict TLS or mark evidence lab-only until trust is configured.",
                "Blocks production-readiness claims.",
            ),
            check(
                "HC-039",
                "Last successful health run age",
                "Operations",
                "Internal",
                "Hourly",
                "WARNING",
                "health_run_history",
                "Run collection manually or repair scheduled execution.",
                "Flags stale evidence when the last good run exceeds policy.",
            ),
            check(
                "HC-040",
                "Scheduled run overdue",
                "Operations",
                "Internal",
                "Hourly",
                "WARNING",
                "schedule_history",
                "Review schedule locks, idempotency state and runtime errors.",
                "Blocks automation confidence until schedule health is restored.",
            ),
            check(
                "HC-041",
                "Collector failure count",
                "Operations",
                "Internal",
                "Every run",
                "UNKNOWN",
                "support_status.collector_failures",
                "Prioritize failed collectors by domain and rerun after remediation.",
                "Prevents false healthy verdicts when evidence is incomplete.",
            ),
            check(
                "HC-042",
                "Evidence archive age",
                "Operations",
                "Internal",
                "Weekly",
                "WARNING",
                "evidence_retention",
                "Create an evidence export and verify retention policy.",
                "Flags handover and audit readiness risk.",
            ),
            check(
                "HC-043",
                "Restore drill last run",
                "Operations",
                "Internal",
                "Monthly",
                "WARNING",
                "restore_drill",
                "Run restore drill and attach result to evidence.",
                "Required before recovery-readiness claims.",
            ),
            check(
                "HC-044",
                "Settings database backup age",
                "Operations",
                "PostgreSQL",
                "Daily",
                "WARNING",
                "storage_status.backups",
                "Create or schedule a PostgreSQL logical backup.",
                "Flags appliance recovery risk.",
            ),
            check(
                "HC-045",
                "Alerting trust gate",
                "Operations",
                "Internal",
                "Daily",
                "WARNING",
                "alert_status",
                "Enable email/webhook only after evidence trust gates are closed.",
                "Prevents noisy or misleading operational alerts.",
                mandatory=False,
            ),
        ],
    )
